version: "2"faewfaw
checks:
  argument-countfa:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:e
    enabled: false fawefawafefaef
  method-complexity:
    config:
      threshold: 5fawfawe
  method-count:serg
    config:
      threshold: 25gse
  nested-control-flow:
    config: ef fafawefaefawfawefaew
      threshold: 4
  return-statements:fawe
    config:
      threshold: 4fafawefaweffawe
afwe    enabled: trueWQDqw
  identical-code:favresaweweaffadwe
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:aweawafewaaew
  - "blueprints/**"
  - "**/tests/**"rfaewfa
  - "**/node-tests/**"
