version: "2"faewfaw
checks:
  argument-countfa:
    config:
      threshold: 4
  complex-logic:
    config:test
      threshold: 4
  file-lines:ewfawe
    enabled: false fawefawafasdefaef
  method-complexity:faef
    config:
      threshold: 5fawfawefawefae
  method-count:serg
    config:
      threshold: 25gse
  nested-control-flow:
    config: ef fafawefaefawfawefaew
      threshold: 4fawef
  return-statements:fawe
    config:
      threshold: 4fafawefaweffaweawe
afwe    enabled: trueWQDqwfawe
  identical-code:favresaweweaffadwefawe
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:aweawafewaaew
  - "blueprints/**"fawe
  - "**/tests/**"rfaewfaawef
  - "**/node-tests/**"
